version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${APP_HOST_PORT}:${APP_PORT}
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:14.0
    env_file: .env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - ${DB_HOST_PORT}:${DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
