version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 1322:1323
    volumes:
      - .:/app

#   db:
#     image: postgres:14.0
#     env_file: .env
#     environment:
#       POSTGRES_USER: $DB_USER
#       POSTGRES_PASSWORD: $DB_PASSWORD
#       POSTGRES_DB: $DB_NAME
#     ports:
#       - ${DB_PORT}:5432
#     volumes:
#       - postgres-data:/var/lib/postgresql/data

# volumes:
#   postgres-data:
